In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline 

In [9]:
from sklearn.datasets import make_classification

In [10]:
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [11]:
pd.DataFrame(X)

0         1         2  ...         7         8         9
0    0.964799 -0.066449  0.986768  ... -1.210161 -0.628077  1.227274
1   -0.916511 -0.566395 -1.008614  ... -0.984534  0.363896  0.209470
2   -0.109484 -0.432774 -0.457649  ... -0.246383 -1.058145 -0.297376
3    1.750412  2.023606  1.688159  ... -0.357445 -1.473127 -0.190039
4   -0.224726 -0.711303 -0.220778  ... -0.939156  0.175915  0.236224
..        ...       ...       ...  ...       ...       ...       ...
995 -1.367638  1.462255 -1.154918  ...  1.428760  1.687092  1.072542
996 -1.514876 -3.221016 -1.300744  ... -1.680870  1.798510  0.034272
997  1.674633  1.754933  1.586154  ...  0.692723 -1.503850  0.225264
998 -0.778609 -0.835689 -0.194842  ... -0.497354  2.472138  0.867187
999  0.248454 -1.003439  0.360460  ...  0.773240  0.185734  1.416412

[1000 rows x 10 columns]

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=55)

In [13]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression( )


In [14]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [15]:
y_pred=logistic.predict(X_test)
print(y_pred)

[1 0 1 1 1 1 1 0 1 1 0 1 0 1 0 0 1 1 1 0 0 0 0 1 1 1 0 0 0 0 1 0 1 1 0 0 0
 1 1 1 1 0 1 1 0 1 0 1 1 1 1 0 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0 0 0 1 0 0 1 1
 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 1
 0 1 0 1 0 0 0 1 1 0 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 1 0 0 0 1 0 1 0 1 1
 1 1 1 0 0 0 0 1 0 1 0 0 0 1 0 1 1 1 0 0 1 1 1 1 0 1 0 0 0 1 1 0 0 0 0 1 1
 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 1 0 0 1 1 1 0 0 0 1 1 0 1 1 1 0 1 1 0 1 1 0
 1 0 1 0 1 1 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 1 1 0 0 0 1 0 1 1 0 1 0 0 1 1 1
 1 0 0 1 1 0 0 0 1 0 1 1 0 0 1 1 0 1 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 1 0 0 0
 1 1 0 1]


In [16]:
logistic.predict_proba(X_test)

array([[3.59825382e-01, 6.40174618e-01],
       [6.20095935e-01, 3.79904065e-01],
       [4.94531888e-02, 9.50546811e-01],
       [3.33835118e-01, 6.66164882e-01],
       [9.97172526e-03, 9.90028275e-01],
       [2.37079492e-01, 7.62920508e-01],
       [1.75636096e-01, 8.24363904e-01],
       [9.87971313e-01, 1.20286868e-02],
       [1.67053861e-01, 8.32946139e-01],
       [2.96799180e-01, 7.03200820e-01],
       [9.08987246e-01, 9.10127539e-02],
       [3.48708461e-02, 9.65129154e-01],
       [9.21135190e-01, 7.88648101e-02],
       [1.21255426e-02, 9.87874457e-01],
       [7.20802495e-01, 2.79197505e-01],
       [8.75147342e-01, 1.24852658e-01],
       [4.94842529e-02, 9.50515747e-01],
       [3.23812117e-02, 9.67618788e-01],
       [2.06113142e-03, 9.97938869e-01],
       [9.07699377e-01, 9.23006232e-02],
       [9.75809715e-01, 2.41902852e-02],
       [9.35892036e-01, 6.41079636e-02],
       [9.66540988e-01, 3.34590116e-02],
       [2.93516828e-02, 9.70648317e-01],
       [3.849913

In [17]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [18]:
score=accuracy_score(y_pred,y_test)
print(score)
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.85
              precision    recall  f1-score   support

           0       0.89      0.81      0.85       153
           1       0.82      0.89      0.85       147

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300

[[124  29]
 [ 16 131]]


In [19]:
model =LogisticRegression()
penalty=['l1', 'l2', 'elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

In [20]:
params=dict(penalty=penalty,C=c_values,solver=solver)

In [21]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [22]:
## GridSearchCV
from sklearn.model_selection import GridSearchCV

grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [23]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [24]:
grid.fit(X_train,y_train)

C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundatio

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [25]:
grid.best_score_

np.float64(0.8657142857142857)

In [26]:
y_pred=grid.predict(X_test)

In [27]:
score=accuracy_score(y_pred,y_test)
print(score)
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.85
              precision    recall  f1-score   support

           0       0.89      0.81      0.85       153
           1       0.82      0.89      0.85       147

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300

[[124  29]
 [ 16 131]]


In [28]:
from sklearn.model_selection import RandomizedSearchCV

In [29]:
model=LogisticRegression()
randomcv=RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,scoring='accuracy')

In [30]:
randomcv.fit(X_train,y_train)

C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.P

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [31]:
randomcv.best_score_

np.float64(0.8657142857142857)

In [32]:
randomcv.best_params_

{'solver': 'liblinear', 'penalty': 'l2', 'C': 1.0}

In [33]:
y_pred=randomcv.predict(X_test)

In [34]:
score=accuracy_score(y_pred,y_test)
print(score)
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.85
              precision    recall  f1-score   support

           0       0.89      0.81      0.85       153
           1       0.82      0.89      0.85       147

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300

[[124  29]
 [ 16 131]]
